on:
  push:
    branches:
      - main

jobs:
  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.foo.outputs.matrix }}
    steps:
      - id: foo
        uses: julianbrost/test-actions-set-matrix-output@main
        
      - shell: bash
        run: echo '${{ steps.foo.outputs.matrix }}'

  test:
    name: ${{ matrix.database.name }}
    needs: get_matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        database: ${{ fromJSON(needs.get_matrix.outputs.matrix) }}

    steps:
      - shell: bash
        run: echo ${{ matrix.database.image }}
