on:
  push:
    branches:
      - main

jobs:
  matrix:
    uses: julianbrost/test-actions-set-matrix-output/.github/workflows/matrix.yml@main

  test:
    name: ${{ matrix.database.name }}
    needs: matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        database: ${{ fromJSON(needs.matrix.outputs.matrix) }}

    steps:
      - shell: bash
        run: echo ${{ matrix.database.image }}
